### ISSUE TITLE
Aceproxy, Mips & Ubuntu 14.04 

### ISSUE THREAD

**Issue by jamescraig81** [ValdikSS/aceproxy#27]
Hello, 

Still hoping to get acestream working on vu duo2 set top box (mips) which has a port of xbmc installed. I have giving up with W7 and installed ubuntu 14.04.. 
Installed acestream & proxy and all dependancies.. but still have an issue,..

I started engine -

james81@UX:~$ acestreamengine --client-console --bind-all
/usr/lib/python2.7/dist-packages/pkg_resources.py:1049: UserWarning: /home/james81/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
2015-01-19 00:13:58,295|MainThread|acestream|platform=linux
2015-01-19 00:13:58,296|MainThread|acestream|app=acestream
2015-01-19 00:13:58,296|MainThread|acestream|version=3.0.3 code=3000300 revision=1355 date=2014-10-31
2015-01-19 00:13:58,296|MainThread|acestream|use_local_db=True
2015-01-19 00:13:58,296|MainThread|acestream|use_m2crypto=True
2015-01-19 00:13:58,296|MainThread|acestream|enable debug: 0
2015-01-19 00:13:58,297|MainThread|acestream|get_default_api_version: 2
2015-01-19 00:13:58,297|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2015-01-19 00:13:58,333|MainThread|acestream.coreapp|cannot load session config, use default
2015-01-19 00:13:58,365|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:56933
2015-01-19 00:13:58,365|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2015-01-19 00:13:58,366|MainThread|acestream.LM|listen on 8621
2015-01-19 00:13:58,378|MainThread|acestream.VideoServer|start: addr= port=6878
2015-01-19 00:13:58,396|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:43112
2015-01-19 00:13:58,397|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2015-01-19 00:13:58,397|Instance2InstanceThread-24|acestream.APIServer|run: ready to receive remote commands on 62062

I then started VLC -

james81@UX:~$ vlc -I telnet --clock-jitter -1 --network-caching -1 --sout-mux-caching 2000 --telnet-password admin
VLC media player 2.2.0-pre2 Weatherwax (revision 2.2.0-pre1-15-g5178b24)
[0000000001bb8658] [telnet] lua interface: Listening on host "telnet://localhost:4212".

Then I start aceproxy - 

james81@UX:~$ python acehttp.py
python: can't open file 'acehttp.py': [Errno 2] No such file or directory
james81@UX:~$ cd aceproxy
james81@UX:~/aceproxy$ python acehttp.py
19.01.2015 00:14:53 DEBUG INIT: Plugin loaded: Torrenttv
19.01.2015 00:14:53 DEBUG INIT: Plugin loaded: Stat
19.01.2015 00:14:53 DEBUG INIT: Plugin loaded: P2pproxy
19.01.2015 00:14:53 DEBUG INIT: Plugin loaded: Torrenttelik
Traceback (most recent call last):
  File "acehttp.py", line 486, in <module>
    server = HTTPServer((AceConfig.httphost, AceConfig.httpport), HTTPHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use
james81@UX:~/aceproxy$ 

Seems to be conflict?

**Comment by miltador** [comment]
socket.error: [Errno 98] Address already in use

Seems like httpport defined in aceconfig.py is busy. Try to reboot server or change it.

**Comment by jamescraig81** [comment]
Hi I think its running on PC now, but cant get the xbmc acestream to connect

Heres a breakdown of everything I can think of...

In order from seperate terminals -

1. Run ace engine

james81@UX:~$ acestreamengine --client-console --bind-all
/usr/lib/python2.7/dist-packages/pkg_resources.py:1049: UserWarning: /home/james81/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
2015-01-19 16:20:35,734|MainThread|acestream|platform=linux
2015-01-19 16:20:35,734|MainThread|acestream|app=acestream
2015-01-19 16:20:35,734|MainThread|acestream|version=3.0.3 code=3000300 revision=1355 date=2014-10-31
2015-01-19 16:20:35,735|MainThread|acestream|use_local_db=True
2015-01-19 16:20:35,735|MainThread|acestream|use_m2crypto=True
2015-01-19 16:20:35,735|MainThread|acestream|enable debug: 0
2015-01-19 16:20:35,737|MainThread|acestream|get_default_api_version: 2
2015-01-19 16:20:35,739|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2015-01-19 16:20:35,801|MainThread|acestream.coreapp|cannot load session config, use default
2015-01-19 16:20:35,970|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:59439
2015-01-19 16:20:35,971|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2015-01-19 16:20:35,971|MainThread|acestream.LM|listen on 8621
2015-01-19 16:20:36,065|MainThread|acestream.VideoServer|start: addr= port=6878
2015-01-19 16:20:36,083|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:51277
2015-01-19 16:20:36,084|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2015-01-19 16:20:36,084|Instance2InstanceThread-24|acestream.APIServer|run: ready to receive remote commands on 62062

2. Run VLC

james81@UX:~$ vlc -I telnet --clock-jitter -1 --network-caching -1 --sout-mux-caching 2000 --telnet-password admin
VLC media player 2.2.0-pre2 Weatherwax (revision 2.2.0-pre1-15-g5178b24)
[0000000001ff2618] [telnet] lua interface: Listening on host "telnet://localhost:4212".

3. Run aceproxy

james81@UX:~$ cd aceproxy
james81@UX:~/aceproxy$ python acehttp.py
19.01.2015 16:21:05 DEBUG INIT: Plugin loaded: Torrenttv
19.01.2015 16:21:05 DEBUG INIT: Plugin loaded: Stat
19.01.2015 16:21:05 DEBUG INIT: Plugin loaded: P2pproxy
19.01.2015 16:21:05 DEBUG INIT: Plugin loaded: Torrenttelik
19.01.2015 16:21:05 DEBUG VlcClient_init: Successfully connected with VLC socket!
19.01.2015 16:21:05 INFO VlcClient_recvData: Authentication successful
19.01.2015 16:21:05 INFO HTTP: Using gevent 1.0
19.01.2015 16:21:05 INFO HTTP: Using psutil 2.1.1
19.01.2015 16:21:05 INFO HTTP: Using VLC VLC media player 2.2.0-pre2 Weatherwax
19.01.2015 16:21:05 INFO HTTP: Server started.

Heres my current settings:

Internet:

Router - 192.168.1.1
XBMC IP - 192.168.1.105
Ubuntu IP - 192.168.1.101
+No open ports on router

Aceconfig.py:

    # Ace Stream Engine configuration
    #
    # acehost = '127.0.0.1'
    # Ace Stream Engine port (autodetect for Windows)
    aceport = 62062  

&

    # AceProxy configuration---
    #
    # HTTP Server host
    httphost = '0.0.0.0'
    # HTTP Server port
    httpport = 8003

+ setting advised in wiki vlcuse, videoobey etc 

XBMC Aceproxy config menu:

Connection IP - 192.168.101
Connection Port - 8003

I could send / paste the xbmc.log if that would be of help.

Heres a section from the xbmc.log when i tried to open a stream:

17:09:05 T:1980481536   DEBUG: OnKey: return (0xf00d) pressed, action is Select
17:09:05 T:1980481536   DEBUG: RunScriptWithParams - calling plugin p2p-streams('plugin://plugin.video.p2p-streams/','-1','?url=acestream%3A%2F%2Fcbf502f1fb6952def64000fe7745bef9cbbbe3ec&mode=1&name=BT+Sport+2+&iconimage=%2Fmedia%2Fhdd%2F.xbmc%2Faddons%2Fplugin.video.p2p-streams%2Fresources%2Fcore%2Fparsers%2Ftorrenttvrusports%2Ficon.png')
17:09:05 T:1551889568  NOTICE: Thread LanguageInvoker start, auto delete: false
17:09:05 T:1551889568    INFO: initializing python engine.
17:09:05 T:1551889568   DEBUG: CPythonInvoker(28, /media/hdd/.xbmc/addons/plugin.video.p2p-streams/default.py): start processing
17:09:05 T:1551889568  NOTICE: -->Python Interpreter Initialized<--
17:09:05 T:1551889568   DEBUG: CPythonInvoker(28, /media/hdd/.xbmc/addons/plugin.video.p2p-streams/default.py): the source file to load is "/media/hdd/.xbmc/addons/plugin.video.p2p-streams/default.py"
17:09:05 T:1551889568   DEBUG: CPythonInvoker(28, /media/hdd/.xbmc/addons/plugin.video.p2p-streams/default.py). **large file path so have deleted this part*******
17:09:05 T:1551889568   DEBUG: CPythonInvoker(28, /media/hdd/.xbmc/addons/plugin.video.p2p-streams/default.py): entering source directory /media/hdd/.xbmc/addons/plugin.video.p2p-streams
17:09:05 T:1551889568   DEBUG: CPythonInvoker(28, /media/hdd/.xbmc/addons/plugin.video.p2p-streams/default.py): instantiating addon using automatically obtained id of "plugin.video.p2p-streams" dependent on version 2.1.0 of the xbmc.python api
17:09:11 T:1551889568  NOTICE: Mode: 1
17:09:11 T:1551889568  NOTICE: URL: acestream://cbf502f1fb6952def64000fe7745bef9cbbbe3ec
17:09:11 T:1551889568  NOTICE: Name: BT Sport 2
17:09:11 T:1551889568  NOTICE: Iconimage: /media/hdd/.xbmc/addons/plugin.video.p2p-streams/resources/core/parsers/torrenttvrusports/icon.png
17:09:11 T:1551889568  NOTICE: Parser: None
17:09:11 T:1551889568  NOTICE: Parserfunction: None
17:09:11 T:1551889568   DEBUG: LocalizeStrings: no strings.po file exist at /media/hdd/.xbmc/addons/plugin.video.p2p-streams/resources/language/English, fallback to strings.xml
17:09:11 T:1551889568   DEBUG: DialogProgress::StartModal called
17:09:11 T:1551889568   DEBUG: ------ Window Init (DialogProgress.xml) ------
17:09:11 T:1551889568    INFO: Loading skin file: DialogProgress.xml, load type: KEEP_IN_MEMORY
17:09:11 T:1551889568   DEBUG: Load DialogProgress.xml: 12.53ms
17:09:11 T:1551889568   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/ImageLib-mips.so)
17:09:11 T:1551889568   DEBUG: Loading: /usr/lib/xbmc/system/ImageLib-mips.so
17:09:11 T:1551889568   DEBUG: Alloc resources: 97.73ms  (13.22 ms skin load)
17:09:14 T:1551889568 WARNING: Attempt to use invalid handle -1
17:09:14 T:1551889568    INFO: CPythonInvoker(28, /media/hdd/.xbmc/addons/plugin.video.p2p-streams/default.py): script successfully run
17:09:14 T:1980481536    INFO: easy_aquire - Created session to http://198.168.1.101
17:09:14 T:1551889568    INFO: Python script stopped
17:09:14 T:1551889568   DEBUG: Thread LanguageInvoker 1551889568 terminating
17:10:14 T:1980481536   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://198.168.1.101:8003/pid/cbf502f1fb6952def64000fe7745bef9cbbbe3ec/stream.mp4
17:10:14 T:1980481536   DEBUG: CCurlFile::GetMimeType - http://198.168.1.101:8003/pid/cbf502f1fb6952def64000fe7745bef9cbbbe3ec/stream.mp4 -> failed

Theres alot more info after this.. just though this might help 

I know this is alot of information I just hope its not too much!

James

**Comment by ValdikSS** [comment]
Please provide full AceProxy log.

**Comment by jamescraig81** [comment]
Sorry but i cant find that file?

**Comment by jamescraig81** [comment]
Tried to find out where that is but there is no mention anywhere on the wiki or in the issues, could you point me in the right direction as to where or how i get the aceproxy log?

Thanks

**Comment by ValdikSS** [comment]
It's printed to stdout when you run aceproxy if you haven't reconfigured it in aceconfig.

**Comment by jamescraig81** [comment]
This can be closed, it works fine. I had left a CMD in the P2P-streams addon config, even though it was set to default and was greayed out when chose your proxy it still reads that and thats why I did not connect with the PC. I 'accidently' moved all setting to default and everything works fine. Thanks for you both for all your help..!

**Comment by ValdikSS** [comment]
Great!
