### ISSUE TITLE
Прокси не стартует

### ISSUE THREAD

**Issue by flomazter** [ValdikSS/aceproxy#54]
выдает такие ошибки 
python aceproxy/acehttp.py
12.05.2016 14:38:35 DEBUG INIT: Plugin loaded: Stat
12.05.2016 14:38:35 DEBUG INIT: Plugin loaded: Torrenttelik
12.05.2016 14:38:35 DEBUG INIT: Plugin loaded: P2pproxy
12.05.2016 14:38:35 DEBUG INIT: Plugin loaded: Torrenttv
12.05.2016 14:38:35 DEBUG INIT: Plugin loaded: Allfon
Traceback (most recent call last):
  File "aceproxy/acehttp.py", line 495, in <module>
    server = HTTPServer((AceConfig.httphost, AceConfig.httpport), HTTPHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in **init**
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use

**Comment by deseven** [comment]
> Address already in use

**Comment by flomazter** [comment]
Так, теперь сервис работает, но не могу понять как запустить воспроизведение фильма из торрента с рутрекера

**Comment by deseven** [comment]
[Информация по использованию](https://github.com/ValdikSS/aceproxy/wiki/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

**Comment by flomazter** [comment]
Инструкцию прочитал всю, вдоль и поперек. Торрент из инструкции работает, а вот с рутрекера нет, например http://rutracker.org/forum/dl.php?t=4639299 (http%3A%2F%2Frutracker.org%2Fforum%2Fdl.php%3Ft%3D4639299)

**Comment by deseven** [comment]
Рутрекер требует авторизацию для скачивания торрентов, так не получится.

**Comment by flomazter** [comment]
Печально, а можно запустить торрент локально скаченный

**Comment by deseven** [comment]
Я бы написал промежуточный скрипт, который авторизуется на рутрекере, качает торрент-файл, запускает веб-сервер и отдает файл AceProxy.
Из быстрых решений можно в нужном каталоге запустить встроенный веб-сервер питона
`python -m SimpleHTTPServer 81`
и отдавать файлы им.
