### ISSUE TITLE
Ace Engine doesn't work. Not in system tray

### ISSUE THREAD

**Issue by garthek** [ValdikSS/aceproxy#57]
Hello. I have a problem with ace stream since a few days. Ace stream not appear at system tray and the ace streams links doesn't work. 
"acestream.log" is here once uninstalled and installed again:

2016-09-19 17:46:26,497|MainThread|acestream|init segmenter done
2016-09-19 17:46:26,497|MainThread|acestream|platform=win32
2016-09-19 17:46:26,497|MainThread|acestream|app=acestream
2016-09-19 17:46:26,497|MainThread|acestream|version=3.1.6 code=3010601 revision=2361 date=2016/05/10 18:17:01
2016-09-19 17:46:26,499|MainThread|acestream|use_local_db=True
2016-09-19 17:46:26,499|MainThread|acestream|use_m2crypto=True
2016-09-19 17:46:26,499|MainThread|acestream|enable debug: 0
2016-09-19 17:46:26,499|MainThread|acestream|get_default_api_version: 2
2016-09-19 17:46:28,673|MainThread|acestream.coreapp|cannot load session config, use default
2016-09-19 17:46:29,898|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:61817
2016-09-19 17:46:29,898|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2016-09-19 17:46:29,898|MainThread|acestream.LM|listen on 8621
2016-09-19 17:46:29,898|MainThread|acestream.localdb|No existing database found. Attempting to creating a new database u'C:\Users\garth\AppData\Roaming\.ACEStream\sqlite\torrentstream.sdb'
2016-09-19 17:46:29,937|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2016-09-19 17:46:29,938|MainThread|acestream.VideoServer|start: addr= port=6879 allow_remote=0 allow_intranet=1
2016-09-19 17:46:29,970|MainThread|acestream|error during startup
Traceback (most recent call last):
  File "core.c", line 1511, in 
  File "core.c", line 367, in 
  File "core.c", line 293, in 
  File "core.c", line 1047, in 
  File "core.c", line 122, in 
  File "core.c", line 289, in 
  File "ACEStream\third_party\zeroconf\zeroconf.pyo", line 1398, in **init**
  File "ACEStream\third_party\zeroconf\zeroconf.pyo", line 1415, in _init_sockets
  File "socket.pyo", line 224, in meth
error: [Errno 10022] Se ha proporcionado un argumento no válido

have you any idea for this issue?

Thanks.

**Comment by deseven** [comment]
Sorry, nobody here is officially supporting Ace Stream. Consider using [official forum](http://forum.torrentstream.org/) instead.
