### ISSUE TITLE
ImportError: No module named gevent

### ISSUE THREAD

**Issue by lexxnsk** [ValdikSS/aceproxy#59]
lexxnsk@debian:~/aceproxy$ python2 ./acehttp.py
Traceback (most recent call last):
  File "./acehttp.py", line 9, in <module>
    import gevent
ImportError: No module named gevent
lexxnsk@debian:~/aceproxy$

вот такая проблема. уже переустановил все, что можно. Пробую в Дебиан Джесси на Виртуалбоксе.

python -c "import gevent; print gevent.__version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gevent
lexxnsk@debian:~/aceproxy$

exxnsk@debian:~/aceproxy$ sudo pip show gevent
Name: gevent
Version: 1.1.2
Summary: Coroutine-based network library
Home-page: http://www.gevent.org/
Author: Jason Madden
Author-email: jason@nextthought.com
License: MIT
Location: /root/.local/lib/python2.7/site-packages
Requires: greenlet
lexxnsk@debian:~/aceproxy$

lexxnsk@debian:~/aceproxy$ python -V
Python 2.7.12
lexxnsk@debian:~/aceproxy$ python2 -V
Python 2.7.12

**Comment by lexxnsk** [comment]
В последующем хочу установить ValdikSS/aceproxy на Raspberry Pi3 для просмотра торрент тв с любых устройств. Это же будет возможно?

**Comment by govg** [comment]
You can change the file /opt/aceproxy/vlcclient/vlcclient.py, edit the gevent.coros line to gevent.lock, and replace the other occurrence of coros with lock.

**Comment by stylemistake** [comment]
This issue was fixed in this fork, and it is more maintained in general: https://github.com/AndreyPavlenko/aceproxy

**Comment by LiguidCool** [comment]
Поставить на малину не выйдет.  На ней не пашет ACE.
